import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#b8c3ff',
        'inverse-on-surface': '#313031',
        'on-tertiary-fixed': '#23005b',
        'surface-bright': '#3a393a',
        'inverse-surface': '#e5e2e3',
        'inverse-primary': '#124af0',
        'surface-dim': '#131314',
        'on-primary-fixed-variant': '#0035be',
        'tertiary-fixed': '#e9ddff',
        'on-secondary-container': '#006a70',
        'on-primary': '#002388',
        'outline': '#8e90a2',
        'background': '#131314',
        'on-tertiary-container': '#f5edff',
        'surface-container-low': '#1c1b1c',
        'on-secondary-fixed': '#002022',
        'primary': '#b8c3ff',
        'on-primary-container': '#efefff',
        'on-primary-fixed': '#001356',
        'on-secondary': '#00363a',
        'surface-variant': '#353436',
        'on-secondary-fixed-variant': '#004f54',
        'primary-fixed': '#dde1ff',
        'outline-variant': '#434656',
        'primary-container': '#2e5bff',
        'secondary-container': '#00f1fe',
        'surface-container-high': '#2a2a2b',
        'on-background': '#e5e2e3',
        'secondary-fixed-dim': '#00dbe7',
        'on-tertiary': '#3c0090',
        'secondary-fixed': '#74f5ff',
        'error': '#ffb4ab',
        'on-surface-variant': '#c4c5d9',
        'error-container': '#93000a',
        'surface': '#131314',
        'on-surface': '#e5e2e3',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-highest': '#353436',
        'on-tertiary-fixed-variant': '#5700c9',
        'primary-fixed-dim': '#b8c3ff',
        'surface-container': '#201f20',
        'on-error': '#690005',
        'tertiary-container': '#803eff',
        'secondary': '#ddfcff',
        'on-error-container': '#ffdad6',
        'tertiary-fixed-dim': '#d1bcff',
        'tertiary': '#d1bcff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'margin-desktop': '64px',
        'unit': '8px',
        'gutter': '24px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
